services:
  node1: # Linia 1 / Coloana 1
    image: gossip # Asigură-te că ai imaginea 'gossip' construită sau disponibilă
    container_name: node1
    environment:
      - NODE_ID=node1
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - INITIAL_VALUE=41.6221 # Valoare random
      - SELF_WEIGHT=0.1988 # c'_11
      - INCOMING_WEIGHTS=node2|0.1551,node4|0.5122,node5|0.1339 # c'_1j, j!=1
      - OUTGOING_PEERS=http://node2:8080,http://node4:8080,http://node5:8080 # k where c'_k1 > 0
    ports:
      - "5001:8080"
    networks:
      - gossip

  node2: # Linia 2 / Coloana 2
    image: gossip
    container_name: node2
    environment:
      - NODE_ID=node2
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - INITIAL_VALUE=13.0630 # Valoare random
      - SELF_WEIGHT=0.2464 # c'_22
      - INCOMING_WEIGHTS=node1|0.3158,node5|0.2127,node8|0.225 # c'_2j, j!=2
      - OUTGOING_PEERS=http://node1:8080,http://node7:8080,http://node8:8080 # k where c'_k2 > 0
    ports:
      - "5002:8080"
    networks:
      - gossip

  node3: # Linia 3 / Coloana 3
    image: gossip
    container_name: node3
    environment:
      - NODE_ID=node3
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - INITIAL_VALUE=41.5728 # Valoare random
      - SELF_WEIGHT=0.4601 # c'_33
      - INCOMING_WEIGHTS=node7|0.2452,node8|0.2947 # c'_3j, j!=3
      - OUTGOING_PEERS=http://node4:8080,http://node5:8080 # k where c'_k3 > 0
    ports:
      - "5003:8080"
    networks:
      - gossip

  node4: # Linia 4 / Coloana 4
    image: gossip
    container_name: node4
    environment:
      - NODE_ID=node4
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - INITIAL_VALUE=49.9968 # Valoare random
      - SELF_WEIGHT=0.4878 # c'_44
      - INCOMING_WEIGHTS=node1|0.1893,node3|0.2106,node7|0.1122 # c'_4j, j!=4
      - OUTGOING_PEERS=http://node1:8080 # k where c'_k4 > 0
    ports:
      - "5004:8080"
    networks:
      - gossip

  node5: # Linia 5 / Coloana 5
    image: gossip
    container_name: node5
    environment:
      - NODE_ID=node5
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - INITIAL_VALUE=16.8719 # Valoare random
      - SELF_WEIGHT=0.1993 # c'_55
      - INCOMING_WEIGHTS=node1|0.296,node3|0.3292,node7|0.1754 # c'_5j, j!=5
      - OUTGOING_PEERS=http://node1:8080,http://node2:8080,http://node6:8080,http://node8:8080 # k where c'_k5 > 0
    ports:
      - "5005:8080"
    networks:
      - gossip

  node6: # Linia 6 / Coloana 6
    image: gossip
    container_name: node6
    environment:
      - NODE_ID=node6
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - INITIAL_VALUE=10.1109 # Valoare random
      - SELF_WEIGHT=0.312 # c'_66
      - INCOMING_WEIGHTS=node5|0.2342,node7|0.2061,node8|0.2477 # c'_6j, j!=6
      - OUTGOING_PEERS=http://node7:8080,http://node8:8080 # k where c'_k6 > 0
    ports:
      - "5006:8080"
    networks:
      - gossip

  node7: # Linia 7 / Coloana 7
    image: gossip
    container_name: node7
    environment:
      - NODE_ID=node7
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - INITIAL_VALUE=30.2167 # Valoare random
      - SELF_WEIGHT=0.2611 # c'_77
      - INCOMING_WEIGHTS=node2|0.3437,node6|0.3952 # c'_7j, j!=7
      - OUTGOING_PEERS=http://node3:8080,http://node4:8080,http://node5:8080,http://node6:8080 # k where c'_k7 > 0
    ports:
      - "5007:8080"
    networks:
      - gossip

  node8: # Linia 8 / Coloana 8
    image: gossip
    container_name: node8
    environment:
      - NODE_ID=node8
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - INITIAL_VALUE=43.1868 # Valoare random
      - SELF_WEIGHT=0.2326 # c'_88
      - INCOMING_WEIGHTS=node2|0.2547,node5|0.2199,node6|0.2929 # c'_8j, j!=8
      - OUTGOING_PEERS=http://node2:8080,http://node3:8080,http://node6:8080 # k where c'_k8 > 0
    ports:
      - "5008:8080"
    networks:
      - gossip

networks:
  gossip:
    # Presupunem că rețeaua 'gossip' există deja (ca în exemplul tău anterior - external: true)
    # Dacă vrei ca docker-compose să o creeze, scoate comentariul de mai jos și șterge 'external: true'
    # driver: bridge
    external: true # Sau elimină această linie dacă vrei ca rețeaua să fie creată de acest fișier compose